### PR TITLE
feat: add icon_url, icon_emoji, and username props

### PR DESCRIPTION
**Pull request by jessefulton**

### CODE REVIEW

**Comment by rafaelverger** [comment]
@jessefulton could you add your changes to README?

@sherzberg , are you watching this repo?

**Comment by jessefulton** [comment]
@rafaelverger I did update the readme - what specifically is missing?

**Comment by rafaelverger** [comment]
@jessefulton I think your changes should be listed in Changelog session

**Comment by sherzberg** [comment]
LGTM! Thanks @jessefulton! @rafaelverger I'll add to the changelog.

**Pull request merged**
